name: Docker publish release

on:
  release:
    types: ["published"]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build
      run: docker build . --tag ${{secrets.DOCKER_USER}}/pubsubhubbubreciever:${{ github.event.release.tag_name }}

    - name: Push
      run: docker push ${{secrets.DOCKER_USER}}/pubsubhubbubreciever
