name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build
      run: docker build . --tag ${{secrets.DOCKER_USER}}/pubsubhubbubreciever:latest

    - name: Push
      run: docker push ${{secrets.DOCKER_USER}}/pubsubhubbubreciever
