name: NugetPublish
on:
  release:
    types: ["published"]

jobs:
  build_and_publish:
    name: Publish to Nuget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6
      - name: Build package
        run: mkdir build && dotnet pack -c Release -o build -p:Version=${{ github.event.release.tag_name }} ./PluginLibrary/PluginLibrary.csproj
      - name: Publish package
        run: dotnet nuget push "build/*" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
      - name: Add to actions as artefact
        uses: actions/upload-artifact@v3
        with:
          name: JulianusIV.PuSHPluginLibrary-${{ github.event.release.tag_name }}.zip
          path: build/*
      - name: Add files to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: build/*
          token: ${{ secrets.GH_TOKEN }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.